site_name: Evo
theme: readthedocs  # Or another theme you prefer

nav:
    - Home: index.md
    - Vision: vision.md
    - Architecture: architecture.md
    - User Guide: user-guide.md
    - Developer Guide: developer-guide.md
    - API Documentation: api-documentation.md
